### ISSUE TITLE
Slow querys

### ISSUE THREAD

**Issue by txs** [gadicc/meteor-messageformat#103]
I'm suffering about having slow translation from my db....
I love the package though. However, it's really slow.
Everyone is using tap:i18n.... should I switch?

Sincerely,

Andy

**Comment by gadicc** [comment]
You should use whatever package best fits your needs.  tap:18n is a fantastic package, but I am still using and developing meteor-messageformat, which addresses my own needs a lot better.  Regarding the speed, I replied to your comment in https://github.com/gadicc/meteor-messageformat/issues/45#issuecomment-85630970.

**Comment by gadicc** [comment]
Closing since this was answered in https://github.com/gadicc/meteor-messageformat/issues/45#issuecomment-85630970 and is fixed in v2.

**Comment by txs** [comment]
Is it possible for the server to push static code of the translation in
server?

Sincerely,

txs

**Comment by gadicc** [comment]
Not 100% sure what you mean... 

If you mean to send the compiled functions instead of using `eval()` on the client side, the answer is yes, but only in v2 :)  There is a `sendCompiled: true` option.   ref: https://github.com/gadicc/meteor-messageformat/issues/104

If you mean to send the translations as text, but in parallel to the initial load via another request (instead of via a Meteor.method like in v0), the answer is yes, but only in v2.

If you meant something else, let me know :>
