### ISSUE TITLE
[v2] Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by almogdesign** [gadicc/meteor-messageformat#125]
Getting the following message 

Uncaught TypeError: Cannot read property 'split' of undefined 

Crashing on locale = locale.split('_')[0];

**Comment by gadicc** [comment]
Mmm I think that code is only in `setLocale()`... can you check to make sure you never call it with an undefined variable / value?  But yes, we should probably handle this case more gracefully.  Either throw an error explaining exactly what happened or perhaps just do nothing without crashing (and a debug level console log).

**Comment by almogdesign** [comment]
So I'm calling set local like so 
```javascript
setLocale = function () {
    msgfmt.setLocale(getUserLanguage());
};
```


And getUserLanguage() has this 
```javascript
getUserLanguage = function(){
    if(Meteor.user()){
        return Meteor.user().locale;
    }
};
```

I'm thinking the user is not ready yet, I can add an else with EN option but then my app would set english when it shouldn't. I'm calling setLocale a lot, for all my form validations

**Comment by gadicc** [comment]
Mmm, yeah, so this would break if the user isn't logged in (`getUserLanguage()` returns undefined) or is logged in but has never called `msgfmt.setLocale()` ever since he was logged in, in which case there's no stored language, and `Meteor.user().locale` will be `undefined`.

I didn't really understand why you need to call setLocale() for validations?  Can't you just let msgfmt handle it for you?  In general we use it when the user clicks on a new language to change to.  It seems a bit weird to set the user's language before they've chosen one, except for when the page loads to the best default.  msgfmt does that all for you, using browser's best suggestion or last saved language (from localStorage) or account on login (if different).

**Comment by almogdesign** [comment]
This is legacy code before the new API's. I updated refactored everything expect the fist setting and for from local. The validation is not related my mistake. 

So there is no need to call  msgfmt.setLocale(getUserLanguage()); on startup?

**Comment by gadicc** [comment]
Nope :)  We handle storing/using a logged in user's locale (unless diabled via the `msgfmt.storeUserLocale` setting).  I'll check to make sure it's documented properly a bit later.  A big goal for v2 was to remove the need of a lot of common code everyone had to do on their own.

**Comment by almogdesign** [comment]
Ok great will remove, also if I'm doing this 

```javascript
// Parsley local
window.ParsleyValidator.setLocale(getLocale());
```
and then 
```javascript
getLocale = function(){
    if(getConnectionStatus()){
        return Meteor.user().locale;
    }
};
```

Would it better jus to use msgfmt.getLocale();

**Comment by gadicc** [comment]
Yup.  When are you calling that though?  On init will be too early for user details, don't forget that `Meteor.user()` is reactive.  But yes, just use the msgfmt functions.  Probably this will cover all your needs:

```js
Tracker.autorun(function() {
  ParsleyValidator.setLocale(msgfmt.locale());
});

**Comment by almogdesign** [comment]
Great everything

**Comment by gadicc** [comment]
Awesome!  I think I'll add this to the README too, useful to know exactly how to integrate with different pacakges.

**Comment by almogdesign** [comment]
Yea that would be great by the way might be good to throw a console error I see people passing null values all the time, easy coding mistake. Maybe even fall back to EN

**Comment by gadicc** [comment]
I changed my mind.  I want it to be super easy to use msgfmt.  From the next version (not yet released), you can remove the above code, we'll integrate with ParsleyValidator automatically.

As for `setLocale()`, we now gracefully handle (i.e. ignore) `null` and `undefined` values.  Better to not fallback to en or native, since most likely it's already been set to the most relevant user for the language.

**Comment by almogdesign** [comment]
So I'm not sure why I was getting the error id you handle null and undefined

**Comment by gadicc** [comment]
Was talking about the next version :)

**Comment by almogdesign** [comment]
Ohh great looking forward to it :)
