### ISSUE TITLE
How to deploy translations from development to production?

### ISSUE THREAD

**Issue by tomitrescak** [gadicc/meteor-messageformat#129]
What's the recommended strategy of deploying the translated strings from development to production? I know of server/mfAll.js file. But what to do next? Thanks.

**Comment by DSpeichert** [comment]
Just have ```server/mfAll.js``` and you are ready to build a release of your app.
If you are using v2, you can also remove the UI.

**Comment by tomitrescak** [comment]
Thanks @DSpeichert , but how?!
What do you mean by removing UI?

**Comment by gadicc** [comment]
If you save mfAll.js and put it in your server directory, and then deploy, the translations should all go across.  That's the only step.  If it's not working it's a bug :)

Re UI, people are using it either for crowd translation on production, or local translation.  For the latter, there's no need to deploy it.  In that case, instead of `msgfmt:ui`, use `msgfmt:ui-dev-only`, and there'll be no translation interface on your deployed instance.

**Comment by rjsmith** [comment]
Hi,

In [V2], do I need to also check into source control the generated `server/extracts.msgfmt` and `server/extracts.msgfmt~` files?  Or should I add them to a `server/.gitignore` file?  I could not find any guidance on this in any of the docs or issues here.   btw - If it's relevant, I intend to deploy the `msgfmt:ui` package to production for some crowd-sourced translation goodness.

Thanks for creating this package,

Richard

**Comment by gadicc** [comment]
Thanks, @rjsmith!  Yes, docs are scarce atm but will be ready before the real v2 release.  Those files can be safely gitignore'd.  Actually in the final release it's going to change a bit, with some changes are finally landing in Meteor 1.2 that I've been waiting for for about 1.5 yrs I think :)   The only file that's used to transfer/backup translations is the mfAll.js file.

**Comment by rjsmith** [comment]
Many thanks for the prompt reply, have added the file names into a  .gitignore file.
