### ISSUE TITLE
Any user can (screw up) translations

### ISSUE THREAD

**Issue by tvld** [gadicc/meteor-messageformat#146]
Right now it seems(?) that **all** users can navigate to */translate* and change text there.  IF this is true, it is a show-stopper, unfortunately and we have to move back to old fashioned i18n.

Should we not do something like :  `mfPkg.init('en', ['admin','editor'] );`  based on *https://github.com/alanning/meteor-roles/*   : an additional parameter with array of the user roles that are allowed to edit text?

**Comment by gadicc** [comment]
Any logged in user being able to change translations is the default behaviour since the two most common cases are either public, crowd sourced translation or devel-only translation without deploying the translation UI (only possible in v2).

As per http://messageformat.meteor.com/docs#security, you can set custom allow/deny funcs to control who has access.  e.g.

```js
mfPkg.webUI.deny(function(userId, doc, fields, modifier) {
  var user = Meteor.users.findOne(userId);
  return !user.isAdmin;
});
```

We go for barebones allow/deny functions because unfortunately there is no uniformity amongst how people are handling roles / access / etc.

**Comment by tvld** [comment]
Yeah, you are right as I noticed. Roles are not in core package. Your code will do fine. Did not figure that out yet... ))
