### ISSUE TITLE
[V2] embedded templates illegal:

### ISSUE THREAD

**Issue by Maxhodges** [gadicc/meteor-messageformat#161]
seems this is not permitted

         {{#mf KEY='visit_our_support_center'}}
                  Visit our {{{supportCenterLink}}} for answers to common questions.
         {{/mf}}

Any suggested workarounds?

**Comment by Maxhodges** [comment]
this works, but seems unnatural for the translator to need to include html in their translation.

         {{#mf KEY='visit_our_support_center'}}
                  Visit our <a class='text-info' href='http://support.whiterabbitexpress.com/' target='_blank'> Help
                  Center
                </a> for answers to common questions.
                {{/mf}}

**Comment by Maxhodges** [comment]
Do I need to just break it down into three parts: before_help_link, html for link, and after_help_link?

**Comment by Maxhodges** [comment]
Here is another example. How would you wrap this in messageFormat?

              I authorize White Rabbit to bill me {{currencyUSD grandTotal}} in order to ship my package.<br/>
                        I agree with the {{{termsOfServiceLink}}}.<br/>
                        <b>I understand that if any customs duty is incurred, it is my responsibility to pay.</b><br/></div>

**Comment by Maxhodges** [comment]
anyone?
bump

**Comment by Maxhodges** [comment]
is the right way like this?

given an existing template `{{{supportCenterLink}}}`

{{#mf KEY='visit_our_support_center' LINK=supportCenterLink}}
              Visit our {LINK} for answers to common questions.
     {{/mf}}

**Comment by gadicc** [comment]
Hey, sorry for the delay, been away on holiday... back today but will take me a little while to catch up on everything (I did sneak in most of the router agnosticism code last night though).

Ok so there are two issues here:

**Template inclusion**

As you noticed, curly braces are part of the MessageFormat standard.  I wouldn't want to do any special hacks for Blaze since some people are using Jade, React, etc.  The "right" way would be to do a {variable} and then have mf figure out that you're passing it a template (maybe possible already with the new sub expression support, haven't checked it out yet, or maybe with specially named variables).  In any event, I'm not sure if it really makes sense to include entire templates inside of a translation, but I'll be open to hear valid use cases.  For your case here, it's a different issue:

**HTML in translations**

It's a matter of taste.  Generally, we try avoid tags in translations:

    <b>{{mf 'something'}}</b>

But small tags are often considered ok, e.g.

    {{mf 'hello' 'Hello <b>there</b>, friend'}}

As you realized, this is more problematic for links, especially since changing the URL invalidates all translations.  The two ways to do it (personally I use the second):

1. `Click {here} to open` where `here` is a helper that returns `'<a>' + mf('linkLabel') + </a>` (like in your last example).

2. `Click {A1a}here{A1b} to open` where A1a and A1b are the open and close tags.

There are some security implications here if you allow HTML but don't trust your translators.  We also need to document this, I'll track this in:  XXX

**Regarding currency**:

This is already built in v2 (not released yet), but there is [no polyfill yet](https://github.com/gadicc/meteor-messageformat/issues/163) for older browsers.  It looks like this:

    {{mf 'total' 'Total: {AMOUNT, number, USD}' AMOUNT=getTotal}}

and once off in JS:

    msgfmt.addFormat('number', { USD: { style: 'currency', currency: 'USD' } });
    msgfmt.addCurrencyShortcut('USD');  // short form of the above

Hope this helps!

**Comment by Maxhodges** [comment]
Sorry but I don't get this

```
Click {here} to open where here is a helper that returns '<a>' + mf('linkLabel') + </a> (like in your last example).

Click {A1a}here{A1b} to open where A1a and A1b are the open and close tags.
```

But I need to translate all the words. In these examples you're only using helpers for the link, not the words 'Click' or 'to open.'

**Comment by Maxhodges** [comment]
`Click {A1a}here{A1b} to open`

so you've left out the mf helper as an exercise for the reader? Should it be

```
{{mf 'foo' 'Click'}}{A1a}{{mf 'myurl' 'here'}}{A1b}{{mf 'bar' 'to open'}}
```

**Comment by gadicc** [comment]
Sorry, that was a poor explanation on my part.  I edited my post above and filled in the gaps a little bit, is it clearer now?

**Comment by Maxhodges** [comment]
yeah, crazy, i didn't know about this option. No in the docs? Definitely should move to docs. Could help a lot of people. 
Thanks!
Will dispatch the Japanese language stuff tomorrow!

**Comment by gadicc** [comment]
Haha, I agree.  Docs are scarce until the real v2 release.  I guess it's time to start working on them though.  I'll try put up something soon, also showing the number formatting stuff.

**Comment by Maxhodges** [comment]
one more time. Ok tried this but I get the literal text 

```
 {{mf 'info_panel_help_link' "Visit our {linka}Help Center{linkb} for answers to common questions." linka="<a class='text-info' href='http://support.example.com/' target='_blank'>" linkb="</a>"}}

```

yields this in the browser

```
Visit our <a class='text-info' href='http://support.whiterabbitexpress.com/' target='_blank'>Help Center</a> for answers to common questions.
```

in the source it's 
```
<p>Visit our &lt;a class='text-info' ...
```
![handle](https://cloud.githubusercontent.com/assets/957271/9678876/8d710624-5324-11e5-9c0a-b6de0e739d9c.png)

Is there some escape sequence so that it doesn't output the literal text?

**Comment by gadicc** [comment]
Ugh, right you are, sorry.  This currently works with a triple-stache `{{{mf}}}` or a block-helper `{{#mf}}`.  I've updated the examples on this page and added them to a staging site with the v2 docs: http://messageformat-v2.meteor.com/examples (at the bottom of the page, the links are broken atm).

In future, we'll require - for block helpers - a `_html=true` attribute, for safety.  I'll track that in https://github.com/gadicc/meteor-messageformat/issues/166.

Thanks for your patience with this... I think everyone will benefit from having the answers already and pushing me a bit with the v2 docs (or at least, the examples).  Incidentally, there are also examples of date, number and currency formatting there too.

**Comment by Maxhodges** [comment]
ah yes, awesome. ok this is working. I tried the triple brackets but was putting them in the wrong place. 

Thank you! This helps a lot!

**Comment by gadicc** [comment]
Sure.  Can't wait for this to all reach stable :>

**Comment by Maxhodges** [comment]
triple-stache can't be used on block helpers?
`{{{#mf 'keyname' foo=bar}}} ...`

**Comment by gadicc** [comment]
Yeah, I said triple-stache **or** block helper :>  Currently the block helper just works as is, but this will be made stricter in the final release.  To avoid needing to make any further changes then, you can simply put the proposed `_html=true` attribute there already, even though it currently has no effect.  See also the examples at the link I gave.

**Comment by Maxhodges** [comment]
OK here I'm mixing a few things. Maybe a good example for others?

```
 <p>
                {{#mf KEY='help_panel_order_link' linka=pathForOrders linkb='<a>'}}
                    If you have a question about an existing order, please
                    contact us from the order detail page. {linka}Go to
                    Orders{linkb}.
                {{/mf}}
            </p>

```

and the helper

```
 pathForOrders: function () {
        return "<a href='" + Router.path('orders') + "' class='text-info'>";
    },
```
