### ISSUE TITLE
Optimization: Should strings be sent as collections?

### ISSUE THREAD

**Issue by DSpeichert** [gadicc/meteor-messageformat#45]
Introduction
=======
Currently, all translations live in collections, are subscribed to by clients and the only strings that always go down the wire are the native ones.

Problem
=======
I've been using this package in "production" for many months now and I concluded that this approach works great on a development server but not on the deployed application server. Even though the strings are reactive, it takes a visible amount of time for the translation to kick in. Other components of the page are not so forgiving and some do not reflect changes of the strings (e.g. rendered DataTables). Language strings are quite essential from the beginning of page load and when there are a lot of other collections to subscribe to, language strings take a long time to load. Setting "policy" to "all" doesn't make any change (it still takes time to load - by design).

Solution
=======
I suggest a better way to do it. It probably doesn't cover all the corners and if implemented, should probably be an optional approach. Here it goes:

Server should interpret Language header from the browser and figure out the best matching language for the user from the list of existing translations. Then, it should embed those translations (and only those, for this one language) in the head of the page, just as it does now for the list of languages only (application/ejson).

Main benefits:
* instant access to localized strings from the first moments
* less collections to subscribe to
* less load on the client to handle translations (right data is sent by the server, no computation required on the client side)

Disadvantages:
* only default, detected language is sent this way (**but it is unlikely that other one would be needed and it is possible to send other languages using the same method**).
* localized strings are static - cannot be dynamically updated (**but who changes translations dynamically on a production site? if really needed, it can be done the current way through subscriptions**)

Larger scope
========
Implementing this method might be a good way to break down meteor-message format into two packages (as already suggested):

1. Development version:
    * uses collections and subscriptions
    * will automatically scan source for changes on restart (Meteor 0.9+)
    * will automatically push changes to clients - strings fully reactive (see #43)
    * will have translation UI

2. Production deployed version
    * will not have translation UI
    * server will load translations from mfAll.js file
    * will embed strings for requested language in head

I think this would be a great performance improvement. Discussion is welcome!

**Comment by txs** [comment]
I love this package but thinking to switch due to the slow subs of translation

**Comment by gadicc** [comment]
You should use whatever package best suits your needs.  I'll use this opportunity though to give an update of what's happening in v2 as per our earlier discussion above:

* Strings are cached in localStorage.  From visit 2 onwards, loading is instant, it looks great.  On future visits, only updated strings are downloaded.
* We don't send inject all the strings (for reasons in earlier comment and above point).
* For first load, we will however have parallel loading (and in light of comments above, an attempt for synchronous loading) of user's best language.  Again, this is only relevant for first load, since from 2nd load everything is cached.
* Not directly related, but yes, in v2, source is automatically checked for changes, both on server restart and client refresh.  We only look at changed files and it's super fast.
* And, not mentioned before, but the other goal for v2 is native offline support, which is also working great.

Although most of the above is implemented, there is still not ETA for v2.  There is a lot of other things that need to be implemented first, and also suitable tests etc.  Consider this more of an update of what's in the works vs what's "around the corner".

**Comment by txs** [comment]
looking good! Thanks!
