### ISSUE TITLE
Allow mf_extract to scan "packages" folder

### ISSUE THREAD

**Issue by lucazulian** [gadicc/meteor-messageformat#89]
I've created a package for my custom login service and inside this package I've used messageformat. When I include this package into another project and launch mf_extract it doesn't scan the my package. Is there a way to set the path of my package into packages folder? I see this in /cli/mf_extract.js

```
var walker  = walk.walk('.', {
    followLinks: false,
    filters: ["packages"]
});
```

but I cannot understand if filters property works or not. Thanks!

**Comment by gadicc** [comment]
Yeah, we intentionally skip this folder because of https://github.com/gadicc/meteor-messageformat/issues/21, however, that's not really an issue in Meteor 0.9+, so I guess we can remove it now :)  Try removing that line and see if it works as you're expecting (it should), although all your keys will still be at the "app level" (as per https://github.com/gadicc/meteor-messageformat/issues/51).  In short, smart package support will be much improved in the upcoming v2.
